import Head from "next/head";
import {Container} from '@chakra-ui/react'

import Hero from "../components/Hero/Hero";
import { ThreeColumnGrid } from "../components/Three Column Grid";

export default function Home() {
  return (
    <Container maxW='container.xl'>
      <Head>
        <title>Subtitle Hero</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <ThreeColumnGrid />
    </Container>
  );
}
