import Head from "next/head";
import { useEffect } from "react";
import { atom, useAtom } from "jotai";

import { Container } from "@chakra-ui/react";

import Hero from "../components/Hero/Hero";
import { ThreeColumnGrid } from "../components/Three Column Grid";

export const userSignedInAtom = atom(false);

export default function Home() {
  const [userAtom, setUserAtom] = useAtom(userSignedInAtom);

  useEffect(() => {
    // console.log("USER RELOGGED IN");
    if (userAtom) {
      return;
    }
    if (localStorage.getItem("currentUserId")) {
      setUserAtom(true);
    }
  }, []);

  return (
    <Container maxW="9xl">
      <Head>
        <title>Subtitle Hero</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <ThreeColumnGrid />
    </Container>
  );
}
